== 约束布局
约束布局是一种自适应布局的方式，就是通过设置一系列的相对布局关系（即约束），来确定每一个组件的位置和大小。iOS和Android开发都支持约束布局（在iOS里叫Auto
Layout；在安卓里叫Constraint
Layout），S2C目前也支持约束布局。在S2C中对约束布局的使用分两种情况：普通模式和特殊模式。

=== 普通模式

普通模式对所有组件都适用。在对界面进行自适应布局时，绝大部分的布局操作都可以在普通模式下完成。

==== 1.基本规则：

1）每个组件（component)都是一个矩形区域。组件有一些属性(attribute)，包括上、下、左、右、水平中心、竖直中心、宽、高（top，bottom，left,
right, centerX, centerY，width, height)。

2）约束是一个或两个组件属性的等式关系。比如component1.aAttribute
== component2.bAttribute + b；或
component1.attribute = b；

3）对一个组件，设置两个水平约束，两个竖直约束。每个组件通过这四个约束来确定自己的位置和大小。
(在插件“布局”面板的上方，有一个示意图，水平约束用蓝色的线表示，竖直约束用红色线表示，这样可以很容易地发现不符合这条规则的情况。)

4）对一个组件的每个属性只能设置一次

比如说在对c1设置约束时，如果设置过c1.left
= c2.left + b1，就不能再设c1.left = c3.right +
b2，这两个在设置c1的约束时只能设置一个。如果想同时有这两个约束，需要在c3上设置
c3.right = c1.left – b2。

==== 2.普通模式下的两种约束

1）两组件约束

两组件约束是一个组件与另一个组件的属性之间的关系。

* 等式：component1.aAttribute
== component2.bAttribute + b

* component2 组件的范围：component1 的父、兄弟和子

* 属性范围： top，bottom，left, right, centerX, centerY。

* aAttribute 和 bAttribute
只能同时是水平属性或竖直属性。不支持component1 .left == component1.top +
b的这种情况。

* aAttribute 和 bAttribute
可以相同也可以不同。
例子：c1.centerY == c2.centerY；c1.left == c2.right + 31；

* 两个组件属性之间关系可以读作依赖于，比如c1.left == c2.right + 31就可以说成c1的left依赖于c2的right。（其实约束关系是互相依赖的，但是这样便于操作）

2）宽高约束

* 等式
：component1.attribute = b

* 属性范围：widht和height

宽高约束分两种情况：

* 固定值。即 component1.attribute
为一个固定的值。比如c1.width = 89

* 按内容。文本组件和图像组件具有两条默认的内容约束。即文本默认具有width
= 文本宽度；height = 文本高度；这两个约束，图像具有 width =
图片宽度；height = 图片高度 这两个约束。

当文本组件和图像组件的宽或高由其它约束决定时，内容约束会被忽略。（也就是说按默认的内容约束比其它约束的优先级低）。

==== 3.设置约束的参考流程

在普通模式下可以参考以下设置约束的流程来对一个页面的所有组件设置约束。

这个可以简单地概括为：从外至内，逐个确定。

下面是设置约束的大概步骤：在一个页面里，contentView的位置和大小是已经确定的，不需要设置约束。在contentView的子组件里选择一个需要设置约束的组件（一般是按着从外到内，从上到下，从左到右的优先次序选择），根据组件布局的“依赖于”关系，找到自身属性依赖于其它确定了的组件属性的所有约束，按着上面的“设置约束的规则”设置约束，使该组件确定。这时确定了的组件就多了一个。然后再选下一个组件，设置约束，逐渐使确定的组件增多，一直到所有组件的位置和大小都确定。（其实一个页面的所有约束是所有相关组件属性关系的整体描述，不存在先后关系，上面步骤里说的这些是为了便于理解和操作）

设置一个两组件约束时，分两种情况：

1）当前组件的某个属性是由外部组件决定时，component2在当前组件的父或者兄弟里选。（这种情况最常见）

2）当前组件的宽或高是由子组件决定时（组件宽或高是由子组件的宽或高撑起来的），component2在当前组件的子组件里选。（这种情况相对少些）

=== 特殊模式

特殊模式需要特殊类型的组件提供支持。目前有以下两种组件（其实是同一种布局模式，即间距固定，高度或宽度相等且自适应）。

1.EqualWidthLayout

这是一个容器，会为它的子组件（子组件要两个或两个以上）设置等宽度约束。布局的结果就是无论容器的宽度、组件之间的间距如何，这些子组件的宽度始终相等。

2.EqualHeightLayout

与上面原理一样，只是布局的结果是组件的高度始终相等。


=== S2C约束布局方案的优点

约束布局是一种很强大的自适应布局方式。但缺点是在实际操作中有时候难掌握，容易把人绕蒙。

S2C提供了一种更容易操作约束的方式，即在普通模式按“从外至内，逐个确定；两个水平约束，两个竖直约束”的方式操作，这即满足了绝大多数场景，又容易操作，容易找错（容易发现组件不满足“两个水平约束，两个竖直约束”的情况）。
如果有人用过XCode Interface Builder来进行过约束设置的话就能体会到这一点。在Android Studio里设置约束也没有清晰的体现出这个特点。

=== 视频演示

上面说的这些有点抽象，可以通过下面的视频来更直观的了解。链接： https://www.bilibili.com/video/BV1rM4y1V7UQ