以下这些视频都是在电脑上的录屏操作，比较适合在电脑上来观看。如果在手机上看，字有可能会显得很小。

== WeiXinDemo

这是一个仿微信界面的Demo。这个视频主要是演示所生成代码的运行效果，没有包括制作设计稿的过程。视频只包含操作，没有声音。

WeiXinDemo视频分3个部分：

1.演示了设计稿中所有页面在预览端预览的效果。

2.演示了生成iOS代码的过程和运行效果。

这个部分先演示了生成并运行一个页面的代码的过程，接下来又演示了生成并运行具有关联关系的所有页面代码的过程
。

3.演示了生成Android代码的过程和运行效果。

视频链接：[https://www.bilibili.com/video/BV1tL411E7Eh]

WeiXinDemo的sketch文件，以及所生成的代码可以从[https://github.com/lianxianghui/S2C-WeiXinDemo]
下载

注：

1.这个设计稿是照着微信界面做的，里面所用的图标是直接从微信界面截图下来的。这些图标的背景不是透明的，这样当点击列表项的时候可以看到有些图标具有白色背景。真实项目设计稿里的图标一般都是是矢量的，可以设置透明背景，就不会出现这种情况。

2.iOS代码运行时，页面最上面的状态栏(statusBar）的效果与设计稿相同。安卓的代码运行时，状态栏的背景色还是项目默认的，要想达到设计稿的效果，目前还需要程序员自行修改.

== DoubleListsDemo

以往有一些工具可以生成UI代码，可是这些工具生成的代码常常与程序员所期望得到的代码有差距，以至于没法直接用。S2C所生成的代码就是按着平时程序员写代码的方式来生成。生成代码后根据需求把动态逻辑（比如获取与展示数据的逻辑）加入即可。

这个视频就是用来演示S2C所生成代码的实用性的。（此视频只包含操作，没有声音）

视频分3个部分：

1.一个手机录屏，内容是我们要参照实现的双栏列表几个动态效果。

2.生成iOS代码，并在其基础上加入实现动态效果的逻辑并运行。

3.生成Android代码，并在其基础上加入实现动态效果的逻辑并运行。

视频链接：[https://www.bilibili.com/video/BV1x64y1e7uf]

Sketch文件，以及代码可以从[https://github.com/lianxianghui/S2C-DoubleListsDemo]
下载。

注：

1.在生成Android代码视频中的14:08-14:15 那里在onClick方法里对itemSelected方法的调用是不必要的。

2.github代码仓库中带modified后缀的目录是指在生成的代码基础上修改过的。不带modified后缀的目录是没修改过的。可以用来对比。

== WeiXinDemoForConvertion

这个视频以一个从网上下载的设计稿页面为例，演示了对原始设计稿进行转换和信息补充(设置布局、属性等），然后使用预览端查看运行效果，最后生成代码并运行的过程。（此视频只包含操作，没有声音）

视频分三个部分：

一、对原始设计稿进行转换和信息补充，然后使用预览端查看运行效果的过程

二、iOS代码生成与运行

三、Android代码生成与运行

视频链接：[https://www.bilibili.com/video/BV1G64y1e7yz]

Sketch文件以及生成的代码可以从[https://github.com/lianxianghui/WeiXinDemoForConvertion]下载

== BasicBitcoinWalletDemo

这是一个用真实项目（BasicBitcoinWallet）的Sketch设计稿来生成代码的演示。

主要是演示所生成代码的运行效果，没有包括制作设计稿的过程。此视频只包含操作，没有声音。

视频分3个部分：

1.演示了设计稿在预览端预览的效果。

2.演示了生成iOS代码的过程和运行效果。

3.演示了生成Android代码的过程和运行效果。

视频链接：[https://www.bilibili.com/video/BV1V3411675X/]

代码可以从[https://github.com/lianxianghui/S2C-BasicBitcoinWalletDemo]下载

注：

BasicBitcoinWallet是一个开源的手机端比特币钱包，目前有iOS版。项目主页：[https://github.com/lianxianghui/BasicBitcoinWallet-iOS]

这个项目的静态界面代码部分就是完全用S2C生成的，这也说明了S2C所生成的代码具有实用性。


